### ISSUE TITLE
limit categories shown on main event page

### ISSUE THREAD

**Issue by cspub** [barryhughes/event-rocket#29]
Love your plugin. Wish I would have found sooner.

I wanted to show our calendar on front page and now I can by selecting main events page in settings/reading. Issue is it shows all our categories. This is for our church and one category, sound, we don't want to display. It shows who is doing sound each day.

How can I limit which categories show on the calendar for front page? I couldn't find where that page is inside dashboard.

thanks

**Comment by barryhughes** [comment]
It's not a page in the classic WordPressy sense.

Think of the main events views as being more akin to category archives - this isn't something you can directly edit, either. The difference here is that the archive is for events (and optionally events in a specific category, etc), rather than blog posts.

Just as if you wanted to do something groovy with a blog archive page, so here the best bet would be to craft a custom snippet to help meet your goals - something like this should give you an idea/serve as a starting point (targeting a hypothetical "comedy" category):

```php
add_action( 'tribe_events_parse_query', 'set_frontpage_event_category' );

function set_frontpage_event_category( $query ) {
	if ( ! $query->get( 'eventrocket_frontpage' ) ) return;
	$query->set( TribeEvents::TAXONOMY, 'comedy' );
}
```
